export const PostTruck = {
  FETCH_START: 'POST_TRUCK_START',
  FETCH_SUCCESS: 'POST_TRUCK_SUCCESS',
  FETCH_FAIL: 'POST_TRUCK_FAIL'
};

export const RemoveTruck = {
  FETCH_START: 'DELETE_TRUCK_START',
  FETCH_SUCCESS: 'DELETE_TRUCK_SUCCESS',
  FETCH_FAIL: 'DELETE_TRUCK_FAIL'
};

export const GetAllTrucks = {
  FETCH_START: 'GET_ALL_TRUCKS_START',
  FETCH_SUCCESS: 'GET_ALL_TRUCKS_SUCCESS',
  FETCH_FAIL: 'GET_ALL_TRUCKS_FAIL'
};

export const UpdateTruck = {
  FETCH_START: 'EDIT_TRUCK_START',
  FETCH_SUCCESS: 'EDIT_TRUCK_SUCCESS',
  FETCH_FAIL: 'EDIT_TRUCK_FAIL'
};